# Generated by Django 5.2.1 on 2025-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
